# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca12a070aec3c189516f5ba9dae63781d80b5baade443b23519a2e67ebaf22e826491c392634ba2d28416282fd4eaab9724188d9040f147a56dd8ad98ed59fcb

test:
  secret_key_base: e57d062ce2a6cb8725b9b65ad9e92e7908f63ce5f46ce4636592e199de738e289e12dadcf71cd1f15a4a9574d8ebdd6e27f95630ff06f53c6732129e949ac22d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
